language: java

sodu: required
services:
    - docker

before_install:
    - docker build -t mesfandi/hw2 .

script:
    #- docker run mesfandi/CS645Homework2
    - echo "skipping tests"

after_success:
    - docker build -t mesfandi/hw2 .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push mesfandi/hw2
